### PR TITLE
Maintain Vehicle Parking Destinations (Issue #30)

### PR DESCRIPTION
**Pull request by rhaetional**
### Reason for Pull Request
This Pull Request resolves the issue #30 

### Background

AutoDrive (ref. Release 2.0.1.4) stores a vehicle's parking destination in the attribute `parkDestination` in _vehicles.xml_:
```
<vehicle id="13" />
    <AutoDrive parkDestination="43"/>
</vehicle>
<vehicle id="14" />
    <AutoDrive parkDestination="43"/>
</vehicle>
``` 

The parking destination corresponds to the sequence index used to store the map markers under `<mapmarker>` in _AutoDrive_config.xml_. For example, the two vehicles above point to the following map marker (id=43):
```
<mm43>
    <id>7917.000000</id>
    <name>PTL 11 - Truck I</name>
    <group>Parking Trailer</group>
</mm43>
``` 

This list is created (and re-indexed) every time the game is saved. If a marker is removed, all markers that followed it in the list will get a new index, and any vehicle that used the deleted or subsequent markers as parking destination will now point to the wrong marker.

Consequently, the attribute  `vehicles.xml: /vehicles/vehicle/AutoDrive/@parkDestination` needs to be kept aligned with its marker's relative position in `AutoDrive_config.xml: /AutoDrive/mapmarker/`.

### Implementation

Extended GameXML with two functions to load and save a vehicle's parking destination:  
image

#### AutoDriveEditor.XMLConfig.GameXML._loadVehiclesXMLParking_
Reads _vehicles.xml_ and generates a map of vehicles parking at a specific marker. The applicable vehicle IDs are then stored in the MapMarker as `GameXML.loadGameXMLFile()` generates them.

 #### AutoDriveEditor.XMLConfig.GameXML._saveVehiclesXMLParking()_
For each marker, its stored vehicleIDs and its current "marker ID" are collected as `GameXML.saveGameXMLFile()` creates the `<mapmarkers>`. `GameXML.saveVehiclesXMLParking()` then uses these to update the `parkDestination` for the relevant vehicles. This is done by first removing all tags and then creating them anew - akin to the logic used for `<mapmarkers>`.

### Nota Bene

- I could only verify this functionality for Farming Simulator 22. To err on the side of data integrity, this feature is only enabled for FS22. 
- Due to the dependency on _vehicles.xml_, this feature only works for a savegame. In practice, it checks for _vehicles.xml_ in the same directory as the loaded config file. 
- Routes Manager XML works independently from specific savegames. So, by design, it does not store or maintain vehicle information, including parking destinations.
- Debug logging is enabled together with "Log XML Config Debug" <br/>image

### CODE REVIEW

**Comment by rhaetional** [comment]
Added it as a draft request, as I think there should be some more testing done against FS19 configurations, etc.

**Comment by KillBait** [comment]
Just doing some quick testing myself.. No issues so far, will let you know if i find anything
Parking

**Comment by rhaetional** [comment]
Looking great there :-)

**Comment by KillBait** [comment]
i'm not sure what code you changed for testing this on FS19.

i modified 2 parts of loadVehiclesXMLParking()

Screenshot1
Screenshot2

i modified 3 parts of saveVehiclesXMLParking()

Screenshot1
Screenshot2
Screenshot3

I spent something like 2 hours repeatedly modifying multiple samegame configs by deleting markes/nodes and reloading the
save, then going through all vehicles with parking spots and getting them to re-navigate the network, i didn't encounter one
error, i did visual checks on all the vehicle XML files by comparing the before and after saving and everything appears to update properly..

**Comment by rhaetional** [comment]
Looks good to me, and I am happy to see that FS19 is now supported, too. 👍 

Can you push your changes to the branch RHAE06?

**Comment by KillBait** [comment]
Releasing v1.07 today

**Pull request closed without merging**
