### PR TITLE
Centre Out-Of-Bounds Nodes functionality (Issue #57)

### PR DESCRIPTION
**Pull request by rhaetional**
### Reason for Pull Request
This Pull Request resolves issue KillBait/AutoDrive_Course_Editor#57

### Description
Adds a new entry to the _Scan_ menu called _"Center Out-Of-Bounds Nodes"_.

After confirmation from the user, it scans for nodes that fall outside the map boundaries. The boundaries are determined based on the dimensions of **mapPanelImage** and the **mapZoomFactor**.

Nodes outside the boundaries are moved to the centre; then, the mapPanel is centred on the first node found. The user can then delete them or modify them as required.

The function supports the undo / redo feature.

### Nota Bene
_Due to the presence of **.gitignore** in the repository, I had to add my own .gitignore to the branch so I don't have to constantly restore it locally. I suggest removing .gitignore from the repository, as it's unrelated to the project._

### CODE REVIEW

**Comment by KillBait** [comment]
Hi [rhaetional](https://github.com/rhaetional),

Thanks a lot for the submission, due to working on other things, i hadn't got around to looking into this
issue yet, i'll get this committed to my dev branch as soon as i can.

Just a side note, i've completely changed how the menu creation code works for the next version, but i can
adjust it to the new system once i merge it in.

Also, i have sorted the issue with the .gitignore, it will be removed on the next commit.

Thanks again for the submission.

**Comment by rhaetional** [comment]
Hi @KillBait 

No worries, I’m happy to contribute.

**Comment by rhaetional** [comment]
Rebased develop/RHAE01_Centre_Out-of-bounds_nodes with .gitignore removed. 

Be sure to update any local copies, if any.

**Comment by KillBait** [comment]
I have manually merged this into my DEV branch, due to the major code changes since the last commit (174 changed files at the moment), i'll close this, but it will be in the next release.

**Pull request closed without merging**
